
compile-job:
  stage: build
  script:
    - rails -B

test-job:
  stage: test
  script:
    - rails test

deploy-heroku-job:
  stage: deploy
  script:
    - dpl --provider=heroku --app=limitless-temple-80750 --api-key=$heroku_key
