

test-job:
  stage: test
  script:
    - export PATH="$PATH:$HOME/.rvm/bin"
    - rvm use 3.2.0
    - bundle install
    - export PORT=5432
    - fuser -k $PORT/tcp || true
    - rails db:create
    - rails db:migrate
    - rails test

deploy-heroku-job:
  stage: deploy
  script:
    - export PATH="$PATH:$HOME/.rvm/bin"
    - rvm use 3.2.0
    - bundle install
    - sudo dpl --provider=heroku --app=limitless-temple-80750 --api-key=$heroku_key
