
compile-job:
  stage: build
  script:
    - export PATH="$PATH:$HOME/.rvm/bin"
    - sudo echo $PATH
    - sudo rvm use 3.2.0
    - sudo ruby -v
    - sudo bundle install
    - sudo rails -B

test-job:
  stage: test
  script:
    - sudo export PATH="$PATH:$HOME/.rvm/bin"
    - sudo rvm use 3.2.0
    - sudo bundle install
    - sudo rails test

deploy-heroku-job:
  stage: deploy
  script:
    - dpl --provider=heroku --app=limitless-temple-80750 --api-key=$heroku_key
