
compile-job:
  stage: build
  script:
    - source "$HOME/.rvm/scripts/rvm"
    - sudo rvm use 3.2.0
    - sudo bundle install
    - rails -B

test-job:
  stage: test
  script:
    - source "$HOME/.rvm/scripts/rvm"
    - sudo rvm use 3.2.0
    - sudo bundle install
    - rails test

deploy-heroku-job:
  stage: deploy
  script:
    - dpl --provider=heroku --app=limitless-temple-80750 --api-key=$heroku_key
